name: CI/CD with terraform

on:
  workflow_run:
    workflows: ["CI"]  # Replace with the name of your CI workflow
    types:
      - completed

      
jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}  # Ensure the job runs only if CI succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_wrapper: false

      - name: Set AWS Credentials as Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV

      - name: Terraform Init with Debugging
        run: |
          sleep 10
          cd terraform-aws
          terraform init -reconfigure

      - name: Terraform Apply
        env:
          TF_VAR_image_tag: "1.0.${{ github.run_number }}"
        run: |
          cd terraform-aws
          terraform apply -auto-approve

